[build]
  command = "npm ci --force && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NETLIFY_USE_YARN = "false"
  NPM_CONFIG_CACHE = "/tmp/.npm"
  HUSKY = "0"